// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiLOUytkZJCrQ-9p1iw3v8ssNHU2p0rf8',
    appId: '1:269050538997:web:0c225cf5b3cc05c37a8ebc',
    messagingSenderId: '269050538997',
    projectId: 'food-order-app-945a6',
    authDomain: 'food-order-app-945a6.firebaseapp.com',
    storageBucket: 'food-order-app-945a6.firebasestorage.app',
    measurementId: 'G-2HQ2TYJMMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZrmYTg9p4KOtCk9FBYlDGrpFklcduPqM',
    appId: '1:269050538997:android:34ac190e7f631ce37a8ebc',
    messagingSenderId: '269050538997',
    projectId: 'food-order-app-945a6',
    storageBucket: 'food-order-app-945a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9FDxnys3lTyAE1O8Xeil7paedGrzw25I',
    appId: '1:269050538997:ios:74db4998a171003c7a8ebc',
    messagingSenderId: '269050538997',
    projectId: 'food-order-app-945a6',
    storageBucket: 'food-order-app-945a6.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9FDxnys3lTyAE1O8Xeil7paedGrzw25I',
    appId: '1:269050538997:ios:74db4998a171003c7a8ebc',
    messagingSenderId: '269050538997',
    projectId: 'food-order-app-945a6',
    storageBucket: 'food-order-app-945a6.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiLOUytkZJCrQ-9p1iw3v8ssNHU2p0rf8',
    appId: '1:269050538997:web:b83f046ede0508297a8ebc',
    messagingSenderId: '269050538997',
    projectId: 'food-order-app-945a6',
    authDomain: 'food-order-app-945a6.firebaseapp.com',
    storageBucket: 'food-order-app-945a6.firebasestorage.app',
    measurementId: 'G-XYB1ENGQQ9',
  );

}